---
# tasks file for mysql-replication
- include_tasks: lvm.yml
  when: lvm == True
- include_tasks: install-mysql.yml
- include_tasks: replication-config.yml
- include_tasks: replication.yml
- include_tasks: iptables.yml
  when: configure_IPtables == True