
- name: create replication@localhost user
  mysql_user:
    login_user: root
    login_password: "{{ msyql_root_password }}"
    name: "{{ mysql_replication_user }}"
    host: "localhost"
    password: "{{ mysql_replication_password }}"
    priv: "*.*:REPLICATION CLIENT,REPLICATION SLAVE,RELOAD,CREATE USER,SUPER"
    state: present

- name: create replication user
  mysql_user:
    login_user: root
    login_password: "{{ msyql_root_password }}"
    name: "{{ mysql_replication_user }}"
    host: "{{ groups['mysql-replication'].1 }}"
    password: "{{ mysql_replication_password }}"
    priv: "*.*:REPLICATION CLIENT,REPLICATION SLAVE,RELOAD,CREATE USER,SUPER"
    state: present
  when: role == 'active'

- name: create replication user
  mysql_user:
    login_user: root
    login_password: "{{ msyql_root_password }}"
    name: "{{ mysql_replication_user }}"
    host: "{{ groups['mysql-replication'].0 }}"
    password: "{{ mysql_replication_password }}"
    priv: "*.*:REPLICATION CLIENT,REPLICATION SLAVE,RELOAD,CREATE USER,SUPER"
    state: present
  when: role == 'passive'

- name: create mysql "{{ mysql_username }}" user
  mysql_user:
    login_user: root
    login_password: "{{ msyql_root_password }}"
    name: "{{ mysql_username }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
    state: present

- name: /etc/my.cnf
  template:
    src: templates/my.cnf.active.j2
    dest: /etc/my.cnf
  when: role == 'active'
  notify: "Restart Mysql Service"
  register: restart_active

- name: /etc/my.cnf
  template:
    src: templates/my.cnf.passive.j2
    dest: /etc/my.cnf
  when: role == 'passive'
  register: restart_passive

- name: Restart Mysql Service "Active"
  service:
    name: "{{ Mariadb_Service }}"
    state: restarted
  when: restart_active.changed

- name: Restart Mysql Service "Active"
  service:
    name: "{{ Mariadb_Service }}"
    state: restarted
  when: restart_passive.changed
