---
# defaults file for mysql-replication

RedHat_Packages:
  - gcc
  - mysql-devel  #  Alternative (NOT Tested) -- yum install mariadb-devel
  - mariadb-server
  - mariadb
RedHat_8_Extra_Packages:
  - python3-pip
  - python3-devel
Ubuntu_Packages:
  - mariadb-server
  - python-dev
  - libmysqlclient-dev
  - gcc
Ubuntu_20_Extra_Packages:
  - python3-pip
  - python3-dev
Mariadb_Service: "{{ 'mariadb' if ansible_os_family and ansible_distribution_major_version >= '7'  else 'mysql'}}"

